blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/WVFNWEvuqX
    about: Ask a question on our official Discord!
  - name: Modrinth
    url: https://modrinth.com/plugin/kotlinmc/
    about: View the plugin on Modrinth!